source 'http://rubygems.org'
group :nanoc do
gem 'nanoc'
  gem 'adsf'        
  gem 'fssm'        
  gem 'kramdown'    
  gem 'haml'        
  gem 'less'        
  gem 'pygments.rb'
  gem 'coderay'
  gem 'stringex'    
  gem 'nokogiri'    
  gem 'rainpress'   
  gem 'therubyracer'
  gem 'rpeg-multimarkdown'
  gem 'mime-types'
  gem 'rake'
  gem 'guard-nanoc'
end
#gem 'systemu'
#gem 'mime-types'
